INSERT INTO TIMESHEET (START_DATE,EMPLOYEE_NAME,SUBMITTED) VALUES (CURRENT_TIMESTAMP(),'JOHN',0);
INSERT INTO TIMESHEET (START_DATE,EMPLOYEE_NAME,SUBMITTED) VALUES (CURRENT_TIMESTAMP(),'PAUL',0);
INSERT INTO TIMESHEET (START_DATE,EMPLOYEE_NAME,SUBMITTED) VALUES (CURRENT_TIMESTAMP(),'RINGO',1);
INSERT INTO TIMESHEET (START_DATE,EMPLOYEE_NAME,SUBMITTED) VALUES (CURRENT_TIMESTAMP(),'GEORGE',1);

