CREATE TABLE TIMESHEET(
	SHEET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EMPLOYEE_NAME VARCHAR(100),
	START_DATE TIMESTAMP NOT NULL,
	SUBMITTED BOOLEAN DEFAULT FALSE
);

CREATE TABLE TIMESHEET_DAY(
	TIMESHEET_DAY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	SHEET_ID BIGINT NOT NULL,
	DAY_OF_WEEK INT,
	MINUTES INT
);

ALTER TABLE TIMESHEET_DAY ADD FOREIGN KEY (SHEET_ID) REFERENCES TIMESHEET(SHEET_ID);

